import 'dart:convert';
import 'package:uuid/uuid.dart';

/// Represents a single transaction/deal made by a customer
class CustomerTransaction {
  final String id;
  final DateTime date;
  final List<TransactionItem> items;
  final double totalAmount;
  final double discount;
  final double finalAmount;
  final String paymentMethod; // Cash, Card, etc.
  final String? notes;

  CustomerTransaction({
    required this.id,
    required this.date,
    required this.items,
    required this.totalAmount,
    this.discount = 0.0,
    required this.finalAmount,
    required this.paymentMethod,
    this.notes,
  });

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'date': date.toIso8601String(),
      'items': items.map((i) => i.toJson()).toList(),
      'totalAmount': totalAmount,
      'discount': discount,
      'finalAmount': finalAmount,
      'paymentMethod': paymentMethod,
      'notes': notes,
    };
  }

  factory CustomerTransaction.fromJson(Map<String, dynamic> json) {
    return CustomerTransaction(
      id: json['id'],
      date: DateTime.parse(json['date']),
      items: (json['items'] as List)
          .map((i) => TransactionItem.fromJson(i))
          .toList(),
      totalAmount: (json['totalAmount'] as num).toDouble(),
      discount: (json['discount'] as num?)?.toDouble() ?? 0.0,
      finalAmount: (json['finalAmount'] as num).toDouble(),
      paymentMethod: json['paymentMethod'],
      notes: json['notes'],
    );
  }
}

class TransactionItem {
  final String productId;
  final String productName;
  final int quantity;
  final double unitPrice;
  final double subtotal;

  TransactionItem({
    required this.productId,
    required this.productName,
    required this.quantity,
    required this.unitPrice,
    required this.subtotal,
  });

  Map<String, dynamic> toJson() {
    return {
      'productId': productId,
      'productName': productName,
      'quantity': quantity,
      'unitPrice': unitPrice,
      'subtotal': subtotal,
    };
  }

  factory TransactionItem.fromJson(Map<String, dynamic> json) {
    return TransactionItem(
      productId: json['productId'],
      productName: json['productName'],
      quantity: json['quantity'],
      unitPrice: (json['unitPrice'] as num).toDouble(),
      subtotal: (json['subtotal'] as num).toDouble(),
    );
  }
}

/// Represents the complete Customer Profile
class AuroraCustomer {
  final String id; // UUID
  final String username; // Used for filename: {username}.json
  final String fullName;
  final String phoneNumber;
  final String? avgAgeGroup; // e.g., "18-25", "26-35"
  final List<CustomerTransaction> transactions;
  final Map<String, dynamic> analysis; // KPIs generated by engine
  final List<AnalysisSnapshot> analysisHistory; // NEW: For trend tracking
  final DateTime createdAt;
  final DateTime updatedAt;

  AuroraCustomer({
    required this.id,
    required this.username,
    required this.fullName,
    required this.phoneNumber,
    this.avgAgeGroup,
    List<CustomerTransaction>? transactions,
    Map<String, dynamic>? analysis,
    List<AnalysisSnapshot>? analysisHistory,
    required this.createdAt,
    required this.updatedAt,
  })  : transactions = transactions ?? [],
        analysis = analysis ?? {},
        analysisHistory = analysisHistory ?? [];

  /// Generates KPIs based on transaction history
  Map<String, dynamic> generateAnalysis() {
    if (transactions.isEmpty) {
      return {
        'totalSpent': 0.0,
        'transactionCount': 0,
        'avgOrderValue': 0.0,
        'lastPurchaseDate': null,
        'favoriteProduct': null,
        'status': 'New',
      };
    }

    double totalSpent = transactions.fold(
        0.0, (sum, t) => sum + t.finalAmount);
    int count = transactions.length;
    double avgOrder = totalSpent / count;
    DateTime lastPurchase = transactions
        .map((t) => t.date)
        .reduce((a, b) => a.isAfter(b) ? a : b);

    // Find favorite product
    Map<String, int> productCounts = {};
    for (var t in transactions) {
      for (var item in t.items) {
        productCounts[item.productName] =
            (productCounts[item.productName] ?? 0) + item.quantity;
      }
    }
    String? favoriteProduct = productCounts.entries
        .reduce((a, b) => a.value > b.value ? a : b)
        .key;

    // Determine Status
    String status = 'New';
    if (count > 5) status = 'VIP';
    else if (count > 2) status = 'Regular';
    
    // Check recency (simple logic)
    if (lastPurchase.difference(DateTime.now()).inDays > 90) {
      status = 'At Risk';
    }

    return {
      'totalSpent': totalSpent,
      'transactionCount': count,
      'avgOrderValue': avgOrder,
      'lastPurchaseDate': lastPurchase.toIso8601String(),
      'favoriteProduct': favoriteProduct,
      'status': status,
      'generatedAt': DateTime.now().toIso8601String(),
    };
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'username': username,
      'fullName': fullName,
      'phoneNumber': phoneNumber,
      'avgAgeGroup': avgAgeGroup,
      'transactions': transactions.map((t) => t.toJson()).toList(),
      'analysis': analysis,
      'analysis_history': analysisHistory.map((s) => s.toJson()).toList(),
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
    };
  }

  factory AuroraCustomer.fromJson(Map<String, dynamic> json) {
    return AuroraCustomer(
      id: json['id'],
      username: json['username'],
      fullName: json['fullName'],
      phoneNumber: json['phoneNumber'],
      avgAgeGroup: json['avgAgeGroup'],
      transactions: (json['transactions'] as List?)
              ?.map((t) => CustomerTransaction.fromJson(t))
              .toList() ??
          [],
      analysis: json['analysis'] ?? {},
      analysisHistory: (json['analysis_history'] as List?)
              ?.map((s) => AnalysisSnapshot.fromJson(s))
              .toList() ??
          [],
      createdAt: DateTime.parse(json['createdAt']),
      updatedAt: DateTime.parse(json['updatedAt']),
    );
  }
  
  AuroraCustomer copyWith({
    String? fullName,
    String? phoneNumber,
    String? avgAgeGroup,
    List<CustomerTransaction>? transactions,
    Map<String, dynamic>? analysis,
    List<AnalysisSnapshot>? analysisHistory,
  }) {
    return AuroraCustomer(
      id: id,
      username: username,
      fullName: fullName ?? this.fullName,
      phoneNumber: phoneNumber ?? this.phoneNumber,
      avgAgeGroup: avgAgeGroup ?? this.avgAgeGroup,
      transactions: transactions ?? this.transactions,
      analysis: analysis ?? this.analysis,
      analysisHistory: analysisHistory ?? this.analysisHistory,
      createdAt: createdAt,
      updatedAt: DateTime.now(),
    );
  }
}

/// Snapshot of analysis metrics at a specific point in time for trend tracking
class AnalysisSnapshot {
  final DateTime timestamp;
  final double totalSpent;
  final int transactionCount;
  final double avgOrderValue;
  final String status;

  AnalysisSnapshot({
    required this.timestamp,
    required this.totalSpent,
    required this.transactionCount,
    required this.avgOrderValue,
    required this.status,
  });

  factory AnalysisSnapshot.fromJson(Map<String, dynamic> json) {
    return AnalysisSnapshot(
      timestamp: json['timestamp'] is String 
          ? DateTime.parse(json['timestamp']) 
          : (json['timestamp'] as DateTime),
      totalSpent: (json['total_spent'] ?? 0.0).toDouble(),
      transactionCount: json['transaction_count'] ?? 0,
      avgOrderValue: (json['avg_order_value'] ?? 0.0).toDouble(),
      status: json['status'] ?? 'Unknown',
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'timestamp': timestamp.toIso8601String(),
      'total_spent': totalSpent,
      'transaction_count': transactionCount,
      'avg_order_value': avgOrderValue,
      'status': status,
    };
  }
}
